var RegionLinks ={
  "Алтайский край": "http://stopcovid-19altairegion.tilda.ws/",
  "Амурская область": "https://www.amurobl.ru/posts/news/operativnaya-informatsiya-po-gotovnosti-meduchrezhdeniy-amurskoy-oblasti-v-usloviyakh-pandemii-koron/?sphrase_id=2219119",
  "Архангельская область": "https://dvinaland.ru/covid19/",
  "Астраханская область": "https://stopcovid-19.astrobl.ru/",
  "Белгородская область": "https://belregion.ru/press/news/index.php?ID=39883",
  "Брянская область": "http://old.bryanskobl.ru/region/law/view.php?id=19937",
  "Владимирская область": "https://avo.ru/web/guest/informacia-o-novoj-koronovirusnoj-infekcii-covid-2019",
  "Волгоградская область": "http://www.volgadmin.ru/d/branches/econom/WorkLineCovid",
  "Вологодская область": "https://vologda-oblast.ru/coronavirus/aktualnaya-informatsiya/index.php",
  "Воронежская область": "http://www.voronezh-city.ru/communications/comments/detail/33394",
  "Еврейская автономная область": "http://www.eao.ru/press-tsentr/aktualno/profilaktika-koronavirusa-eao/",
  "Забайкальский край": "https://virus.75.ru/",
  "Ивановская область": "http://www.ivanovoobl.ru/?type=news&id=28083",
  "Иркутская область": "https://irkobl.ru/coronavirus/",
  "Кабардино-Балкарская Республика": "https://pravitelstvo.kbr.ru/koronavirusnaya_infektsiya_covid_19.php?clear_cache=Y",
  "Калининградская область": "https://gov39.ru/koronavirus/",
  "Калужская область": "http://admoblkaluga.ru/main/news/covid19_inform/index.php",
  "Камчатский край": "https://www.kamgov.ru/news/v-kamcatskom-krae-planiruut-prinat-pervyj-antikrizisnyj-paket-regionalnyh-mer-podderzki-predprinimatelej-29747",
  "Карачаево-Черкесия": "https://kchr.ru/newsline/90/",
  "Кемеровская область": "https://covid19.ako.ru/",
  "Кировская область": "https://kirovreg.ru/covid/",
  "Костромская область": "http://www.adm44.ru/drugnovosti/covid19/",
  "Краснодарский край": "https://admkrai.krasnodar.ru/content/1971/",
  "Красноярский край": "http://www.krskstate.ru/virus",
  "Республика Крым": "https://rk.gov.ru/koronavirus",
  "Курганская область": "http://kurganobl.ru/Ofitsialnaya_informatsiya_o_koronaviruse",
  "Курская область": "http://adm.rkursk.ru/index.php?id=2689",
  "Ленинградская область": "https://lenobl.ru/ru/dlya-smi/news/26415/",
  "Липецкая область": "https://wiki.admlr.lipetsk.ru/theme/30",
  "Магаданская область": "https://minzdrav.49gov.ru/press/smi/index.php?id_4=52264",
  "Москва": "https://www.mos.ru/city/projects/covid-19/",
  "Московская область": "https://www.mos.ru/city/projects/covid-19/",
  "Мурманская область": "https://covid.gov-murman.ru/",
  "Нижегородская область": "https://xn--b1acdfjbh2acclca1a.xn--p1ai/Poleznoe-zhitelyam/Koronavirus-COVID-19-Operativnaya-informaciya-i-otvety-na-osnovnye-voprosy",
  "Новгородская область": "https://xn--b1acdfjbh2acclca1a.xn--p1ai/Poleznoe-zhitelyam/Koronavirus-COVID-19-Operativnaya-informaciya-i-otvety-na-osnovnye-voprosy",
  "Новосибирская область": "https://novo-sibirsk.ru/to-citizens/stopkoronavirus/",
  "Омская область": "https://www.admomsk.ru/web/guest/news/covid-19",
  "Оренбургская область": "http://www.orenburg-gov.ru/news/main/gubernator-orenburgskoy-oblasti-denis-pasler-vnyes-izmeneniya-v-ukaz-o-merakh-po-protivodeystviyu-ra/",
  "Орловская область": "https://orel-region.ru/index.php?head=1&op=news&tag=19",
  "Пензенская область": "http://pnzreg.ru/news/koronavirus/",
  "Пермский край": "https://covid19.gorodperm.ru/",
  "Приморский край": "https://www.primorsky.ru/events/koronavirus/",
  "Псковская область": "http://xn--80aesfpebagmfblc0a.xn--b1apmck.xn--p1ai/",
  "Республика Алтай": "http://stopcovid-19altairegion.tilda.ws/",
  "Республика Башкортостан": "https://investrb.ru/ru/",
  "Республика Бурятия": "https://egov-buryatia.ru/informatsiya-o-novoy-koronavirusnoy-infektsii-covid-19/",
  "Республика Дагестан": "https://mydagestan.e-dag.ru/coronavirus/informatsiya-na-29-aprelya-10-30/image/boiling_cook.svg?PAGEN_1=3",
  "Республика Ингушетия": "http://www.ingushetia.ru/president/covid19.php",
  "Республика Коми": "http://rkomi.ru/page/19891/",
  "Республика Марий Эл": "https://opershtab12.ru/",
  "Республика Мордовия": "http://stopvirus.e-mordovia.ru/",
  "Республика Саха (Якутия)": "https://stopcovid19.sakha.gov.ru/",
  "Республика Северная Осетия-Алания": "http://alania.gov.ru/news/8479",
  "Республика Тыва": "http://gov.tuva.ru/%D1%81oronavirus/",
  "Республика Удмуртия": "http://www.udmurt.ru/about/covid19.php",
  "Ростовская область": "https://rostov-gorod.ru/press_room/COVID19/",
  "Рязанская область": "https://www.ryazangov.ru/governmentro/covid-19/",
  "Самарская область": "https://samadm.ru/city_life/coronavirus/",
  "Саратовская область": "https://saratov.gov.ru/gov/coronavirus/doc/",
  "Сахалинская область": "https://sakhalin.gov.ru/?id=6",
  "Свердловская область": "https://xn--b1ag8a.xn--p1ai/%D1%81%D1%82%D0%BE%D0%BF%D0%B2%D0%B8%D1%80%D1%83%D1%81",
  "Смоленская область": "https://www.admin-smolensk.ru/koronavirus/",
  "Ставропольский край": "https://stavregion.ru/informaciya-o-covid-19/",
  "Тамбовская область": "https://www.tambov.gov.ru/news/v-delovom-prostranstve-geometriya-biznesa-rabotayut-goryachie-linii-po-voprosam-podderzhki-biznesa.html",
  "Татарстан": "http://prav.tatarstan.ru/rus/covid-19-v-respublike-tatarstan.htm",
  "Тверская область": "https://tverreg.ru/covid19/",
  "Томская область": "https://www.tomsk.gov.ru/pages/front/view/id/31048",
  "Тюменская область": "https://admtyumen.ru/ogv_ru/block/hottopic/headquarters.htm",
  "Ульяновская область": "https://ulgov.ru/page/index/permlink/id/19432/",
  "Хабаровский край": "https://khabkrai.ru/events/news/178139",
  "Хакасия": "https://xn--80aesfpebagmfblc0a.xn--80aayg0bu9e.xn--p1ai/",
  "Ханты-Мансийский автономный округ": "https://myopenugra.ru/news/covid-19/",
  "Челябинская область": "https://cheladmin.ru/ru/glavnaya-stranica/ostavaytesdoma",
  "Чеченская Республика": "http://chechnya.gov.ru/novosti/bolee-160-tysyach-semej-chr-poluchili-pomoshh-rof-s-nachala-pandemii-v-rossii/",
  "Чукотский автономный округ": "http://87.rospotrebnadzor.ru/",
  "Чувашская Республика": "http://medicin.cap.ru/action/activity/organizaciya-medicinskoj-pomoschi-vzroslomu-nasele/profilaktika/profilaktika-rasprostraneniya-novoj-koronavirusnoj/goryachaya-liniya-dlya-grazhdan-vernuvshihsya-s-te",
  "Ямало-Ненецкий автономный округ": "https://sever-press.ru/covid/",
  "Ярославская область": "https://vk.com/koronavirus76",






};
