var RegionLinks ={
  "Алтайский край": "http://stopcovid-19altairegion.tilda.ws/",
  "Амурская область": "",
  'Архангельская область': "https://dvinaland.ru/covid19/",
  'Астраханская область': "",
  'Белгородская область': "https://belregion.ru/press/news/index.php?ID=39883",
  'Брянская область': "http://old.bryanskobl.ru/region/law/view.php?id=19937",
  'Владимирская область': "",
  'Волгоградская область': "http://www.volgadmin.ru/d/branches/econom/WorkLineCovid",
  'Вологодская область': "",
  'Воронежская область': "http://www.voronezh-city.ru/communications/comments/detail/33394",
  'Еврейская автономная область': "",
  'Забайкальский край': "https://virus.75.ru/",
  'Ивановская область': "http://www.ivanovoobl.ru/?type=news&id=28083",
  'Иркутская область': "",
  'Кабардино-Балкарская Республика': "",
  'Калининградская область': "",
  'Калужская область': "",
  'Камчатский край': "https://www.kamgov.ru/news/v-kamcatskom-krae-planiruut-prinat-pervyj-antikrizisnyj-paket-regionalnyh-mer-podderzki-predprinimatelej-29747",
  'Карачаево-Черкесия': "",
  'Кемеровская область': "",
  'Кировская область': "",
  'Костромская область': "",
  'Краснодарский край': "https://admkrai.krasnodar.ru/content/1971/",
  'Красноярский край': "http://www.krskstate.ru/virus",
  'Республика Крым': "",
  'Курганская область': "",
  'Курская область': "",
  'Ленинградская область': "https://lenobl.ru/ru/dlya-smi/news/26415/",
  'Липецкая область': "",
  'Магаданская область': "",
  "Москва": "https://www.mos.ru/city/projects/covid-19/",
  'Московская область': "https://www.mos.ru/city/projects/covid-19/",
  'Мурманская область': "",
  'Нижегородская область': "https://xn--b1acdfjbh2acclca1a.xn--p1ai/Poleznoe-zhitelyam/Koronavirus-COVID-19-Operativnaya-informaciya-i-otvety-na-osnovnye-voprosy",
  'Новгородская область': "https://xn--b1acdfjbh2acclca1a.xn--p1ai/Poleznoe-zhitelyam/Koronavirus-COVID-19-Operativnaya-informaciya-i-otvety-na-osnovnye-voprosy",
  'Новосибирская область': "https://novo-sibirsk.ru/to-citizens/stopkoronavirus/",
  'Омская область': "https://www.admomsk.ru/web/guest/news/covid-19",
  'Оренбургская область': "",
  'Орловская область': "",
  'Пензенская область': "",
  'Пермский край': "https://covid19.gorodperm.ru/",
  'Приморский край': "https://www.primorsky.ru/events/koronavirus/",
  'Псковская область': "",
  'Республика Алтай': "http://stopcovid-19altairegion.tilda.ws/",
  'Республика Башкортостан': "https://investrb.ru/ru/",
  'Республика Бурятия': "https://egov-buryatia.ru/informatsiya-o-novoy-koronavirusnoy-infektsii-covid-19/",
  'Республика Дагестан': "https://mydagestan.e-dag.ru/coronavirus/informatsiya-na-29-aprelya-10-30/image/boiling_cook.svg?PAGEN_1=3",
  'Республика Ингушетия': "",
  'Республика Коми': "http://rkomi.ru/page/19891/",
  'Республика Марий Эл': "",
  'Республика Мордовия': "",
  'Республика Саха (Якутия)': "https://stopcovid19.sakha.gov.ru/",
  'Республика Северная Осетия-Алания': "http://alania.gov.ru/news/8479",
  'Республика Тува': "",
  'Республика Удмуртия': "",
  'Ростовская область': "https://rostov-gorod.ru/press_room/COVID19/",
  'Рязанская область': "",
  'Самарская область': "https://samadm.ru/city_life/coronavirus/",
  'Саратовская область': "",
  'Сахалинская область': "https://sakhalin.gov.ru/?id=6",
  'Свердловская область': "",
  'Смоленская область': "",
  'Ставропольский край': "https://stavregion.ru/informaciya-o-covid-19/",
  'Тамбовская область': "https://www.tambov.gov.ru/news/v-delovom-prostranstve-geometriya-biznesa-rabotayut-goryachie-linii-po-voprosam-podderzhki-biznesa.html",
  'Татарстан': "http://prav.tatarstan.ru/rus/covid-19-v-respublike-tatarstan.htm",
  'Тверская область': "",
  'Томская область': "https://www.tomsk.gov.ru/pages/front/view/id/31048",
  'Тюменская область': "",
  'Ульяновская область': "",
  'Хабаровский край': "https://khabkrai.ru/events/news/178139",
  'Хакасия': "https://xn--80aesfpebagmfblc0a.xn--80aayg0bu9e.xn--p1ai/",
  'Ханты-Мансийский автономный округ': "",
  'Челябинская область': "https://cheladmin.ru/ru/glavnaya-stranica/ostavaytesdoma",
  'Чеченская Республика': "http://chechnya.gov.ru/novosti/bolee-160-tysyach-semej-chr-poluchili-pomoshh-rof-s-nachala-pandemii-v-rossii/",
  'Чувашская Республика': "",
  'Ямало-Ненецкий автономный округ': "",
  'Ярославская область': "",
};
